// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// netfilter
arma::mat netfilter(Rcpp::List W, arma::vec rho);
RcppExport SEXP _netpanel_netfilter(SEXP WSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(netfilter(W, rho));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_v
arma::vec gls_compute_v(arma::mat A, arma::vec beta, arma::mat X, arma::vec Y);
RcppExport SEXP _netpanel_gls_compute_v(SEXP ASEXP, SEXP betaSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_v(A, beta, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_beta
arma::vec gls_compute_beta(arma::mat A, arma::mat omegainv, arma::mat X, arma::vec Y, bool random);
RcppExport SEXP _netpanel_gls_compute_beta(SEXP ASEXP, SEXP omegainvSEXP, SEXP XSEXP, SEXP YSEXP, SEXP randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omegainv(omegainvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< bool >::type random(randomSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_beta(A, omegainv, X, Y, random));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_sigma2
double gls_compute_sigma2(arma::vec v, arma::mat omegainv, bool random);
RcppExport SEXP _netpanel_gls_compute_sigma2(SEXP vSEXP, SEXP omegainvSEXP, SEXP randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omegainv(omegainvSEXP);
    Rcpp::traits::input_parameter< bool >::type random(randomSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_sigma2(v, omegainv, random));
    return rcpp_result_gen;
END_RCPP
}
// inv_omega
arma::mat inv_omega(double theta, double n, double t);
RcppExport SEXP _netpanel_inv_omega(SEXP thetaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_omega(theta, n, t));
    return rcpp_result_gen;
END_RCPP
}
// det_omega
double det_omega(double theta, double n, double t);
RcppExport SEXP _netpanel_det_omega(SEXP thetaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(det_omega(theta, n, t));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_random_find
double pnam_ll_random_find(arma::vec Y, arma::mat X, Rcpp::List W, double n, double t, arma::vec rho, double theta);
RcppExport SEXP _netpanel_pnam_ll_random_find(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_random_find(Y, X, W, n, t, rho, theta));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_random
double pnam_ll_random(arma::mat netA, double sigma2, arma::vec v, double n, double t, double theta);
RcppExport SEXP _netpanel_pnam_ll_random(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP nSEXP, SEXP tSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_random(netA, sigma2, v, n, t, theta));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_fixed_find
double pnam_ll_fixed_find(arma::vec Y, arma::mat X, Rcpp::List W, double n, double t, arma::vec rho);
RcppExport SEXP _netpanel_pnam_ll_fixed_find(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_fixed_find(Y, X, W, n, t, rho));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_fixed
double pnam_ll_fixed(arma::mat netA, double sigma2, arma::vec v, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_fixed(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_fixed(netA, sigma2, v, n, t));
    return rcpp_result_gen;
END_RCPP
}
// create_B
arma::mat create_B(arma::mat W2, double lambda);
RcppExport SEXP _netpanel_create_B(SEXP W2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(create_B(W2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// create_LAMBDA
arma::mat create_LAMBDA(arma::mat B);
RcppExport SEXP _netpanel_create_LAMBDA(SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(create_LAMBDA(B));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_e
arma::vec gls_compute_e(arma::mat A, arma::vec beta, arma::mat B, arma::mat X, arma::vec Y);
RcppExport SEXP _netpanel_gls_compute_e(SEXP ASEXP, SEXP betaSEXP, SEXP BSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_e(A, beta, B, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_beta_error
arma::vec gls_compute_beta_error(arma::mat A, arma::mat LAMBDA, arma::mat X, arma::vec Y);
RcppExport SEXP _netpanel_gls_compute_beta_error(SEXP ASEXP, SEXP LAMBDASEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type LAMBDA(LAMBDASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_beta_error(A, LAMBDA, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// gls_compute_sigma2_error
double gls_compute_sigma2_error(arma::vec v, arma::mat omegainv);
RcppExport SEXP _netpanel_gls_compute_sigma2_error(SEXP vSEXP, SEXP omegainvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omegainv(omegainvSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_compute_sigma2_error(v, omegainv));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_fixed_error_find
double pnam_ll_fixed_error_find(arma::vec Y, arma::mat X, Rcpp::List W, double n, double t, arma::vec rho, arma::mat W2, double lambda);
RcppExport SEXP _netpanel_pnam_ll_fixed_error_find(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP W2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_fixed_error_find(Y, X, W, n, t, rho, W2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_fixed_error
double pnam_ll_fixed_error(arma::mat netA, arma::mat B, double sigma2, arma::vec e, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_fixed_error(SEXP netASEXP, SEXP BSEXP, SEXP sigma2SEXP, SEXP eSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_fixed_error(netA, B, sigma2, e, n, t));
    return rcpp_result_gen;
END_RCPP
}
// omega_error
arma::mat omega_error(double theta, double n, double t, arma::mat W2, double lambda);
RcppExport SEXP _netpanel_omega_error(SEXP thetaSEXP, SEXP nSEXP, SEXP tSEXP, SEXP W2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(omega_error(theta, n, t, W2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_random_error_find
double pnam_ll_random_error_find(arma::vec Y, arma::mat X, Rcpp::List W, double n, double t, arma::vec rho, double theta, arma::mat W2, double lambda);
RcppExport SEXP _netpanel_pnam_ll_random_error_find(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP W2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_random_error_find(Y, X, W, n, t, rho, theta, W2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_random_error
double pnam_ll_random_error(arma::mat netA, double sigma2, arma::vec v, arma::mat omega, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_random_error(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP omegaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_random_error(netA, sigma2, v, omega, n, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netpanel_netfilter", (DL_FUNC) &_netpanel_netfilter, 2},
    {"_netpanel_gls_compute_v", (DL_FUNC) &_netpanel_gls_compute_v, 4},
    {"_netpanel_gls_compute_beta", (DL_FUNC) &_netpanel_gls_compute_beta, 5},
    {"_netpanel_gls_compute_sigma2", (DL_FUNC) &_netpanel_gls_compute_sigma2, 3},
    {"_netpanel_inv_omega", (DL_FUNC) &_netpanel_inv_omega, 3},
    {"_netpanel_det_omega", (DL_FUNC) &_netpanel_det_omega, 3},
    {"_netpanel_pnam_ll_random_find", (DL_FUNC) &_netpanel_pnam_ll_random_find, 7},
    {"_netpanel_pnam_ll_random", (DL_FUNC) &_netpanel_pnam_ll_random, 6},
    {"_netpanel_pnam_ll_fixed_find", (DL_FUNC) &_netpanel_pnam_ll_fixed_find, 6},
    {"_netpanel_pnam_ll_fixed", (DL_FUNC) &_netpanel_pnam_ll_fixed, 5},
    {"_netpanel_create_B", (DL_FUNC) &_netpanel_create_B, 2},
    {"_netpanel_create_LAMBDA", (DL_FUNC) &_netpanel_create_LAMBDA, 1},
    {"_netpanel_gls_compute_e", (DL_FUNC) &_netpanel_gls_compute_e, 5},
    {"_netpanel_gls_compute_beta_error", (DL_FUNC) &_netpanel_gls_compute_beta_error, 4},
    {"_netpanel_gls_compute_sigma2_error", (DL_FUNC) &_netpanel_gls_compute_sigma2_error, 2},
    {"_netpanel_pnam_ll_fixed_error_find", (DL_FUNC) &_netpanel_pnam_ll_fixed_error_find, 8},
    {"_netpanel_pnam_ll_fixed_error", (DL_FUNC) &_netpanel_pnam_ll_fixed_error, 6},
    {"_netpanel_omega_error", (DL_FUNC) &_netpanel_omega_error, 5},
    {"_netpanel_pnam_ll_random_error_find", (DL_FUNC) &_netpanel_pnam_ll_random_error_find, 9},
    {"_netpanel_pnam_ll_random_error", (DL_FUNC) &_netpanel_pnam_ll_random_error, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_netpanel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
