// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// omega
arma::mat omega(double theta, double n, double t);
RcppExport SEXP _netpanel_omega(SEXP thetaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(omega(theta, n, t));
    return rcpp_result_gen;
END_RCPP
}
// netfilter
arma::mat netfilter(arma::mat W, double rho);
RcppExport SEXP _netpanel_netfilter(SEXP WSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(netfilter(W, rho));
    return rcpp_result_gen;
END_RCPP
}
// compute_v
arma::vec compute_v(arma::mat A, arma::vec beta, arma::mat X, arma::vec Y);
RcppExport SEXP _netpanel_compute_v(SEXP ASEXP, SEXP betaSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_v(A, beta, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// compute_beta
arma::vec compute_beta(arma::mat A, arma::mat omegainv, arma::mat X, arma::vec Y);
RcppExport SEXP _netpanel_compute_beta(SEXP ASEXP, SEXP omegainvSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omegainv(omegainvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_beta(A, omegainv, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// compute_sigma2
double compute_sigma2(arma::vec v, arma::mat omegainv);
RcppExport SEXP _netpanel_compute_sigma2(SEXP vSEXP, SEXP omegainvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omegainv(omegainvSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma2(v, omegainv));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_rule_search
double pnam_ll_rule_search(arma::vec Y, arma::mat X, arma::mat W, double n, double t, double rho, double theta);
RcppExport SEXP _netpanel_pnam_ll_rule_search(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_rule_search(Y, X, W, n, t, rho, theta));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_rule
double pnam_ll_rule(arma::mat netA, double sigma2, arma::vec v, arma::mat omega, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_rule(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP omegaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_rule(netA, sigma2, v, omega, n, t));
    return rcpp_result_gen;
END_RCPP
}
// omega_rulewae
arma::mat omega_rulewae(double theta, double n, double t, arma::mat W1, double lambda);
RcppExport SEXP _netpanel_omega_rulewae(SEXP thetaSEXP, SEXP nSEXP, SEXP tSEXP, SEXP W1SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(omega_rulewae(theta, n, t, W1, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_rulewae_search
double pnam_ll_rulewae_search(arma::vec Y, arma::mat X, arma::mat W, arma::mat W1, double n, double t, double rho, double theta, double lambda);
RcppExport SEXP _netpanel_pnam_ll_rulewae_search(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP W1SEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_rulewae_search(Y, X, W, W1, n, t, rho, theta, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_rulewae
double pnam_ll_rulewae(arma::mat netA, double sigma2, arma::vec v, arma::mat omega, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_rulewae(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP omegaSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_rulewae(netA, sigma2, v, omega, n, t));
    return rcpp_result_gen;
END_RCPP
}
// netfilter_dpnam
arma::mat netfilter_dpnam(arma::mat W, arma::mat L, double rho, double delta, double phi);
RcppExport SEXP _netpanel_netfilter_dpnam(SEXP WSEXP, SEXP LSEXP, SEXP rhoSEXP, SEXP deltaSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(netfilter_dpnam(W, L, rho, delta, phi));
    return rcpp_result_gen;
END_RCPP
}
// compute_beta_norandom
arma::vec compute_beta_norandom(arma::mat X, arma::mat Y, arma::mat A);
RcppExport SEXP _netpanel_compute_beta_norandom(SEXP XSEXP, SEXP YSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(compute_beta_norandom(X, Y, A));
    return rcpp_result_gen;
END_RCPP
}
// compute_sigma2_norandom
double compute_sigma2_norandom(arma::vec v);
RcppExport SEXP _netpanel_compute_sigma2_norandom(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma2_norandom(v));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_dynam_search
double pnam_ll_dynam_search(arma::vec Y, arma::mat X, arma::mat W, arma::mat L, double n, double t, double rho, double delta, double phi);
RcppExport SEXP _netpanel_pnam_ll_dynam_search(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP LSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP deltaSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_dynam_search(Y, X, W, L, n, t, rho, delta, phi));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_dynam
double pnam_ll_dynam(arma::mat netA, double sigma2, arma::vec v, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_dynam(SEXP netASEXP, SEXP sigma2SEXP, SEXP vSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_dynam(netA, sigma2, v, n, t));
    return rcpp_result_gen;
END_RCPP
}
// B_dpnam
arma::mat B_dpnam(arma::mat B, double lambda);
RcppExport SEXP _netpanel_B_dpnam(SEXP BSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(B_dpnam(B, lambda));
    return rcpp_result_gen;
END_RCPP
}
// compute_beta_norandom_wae
arma::vec compute_beta_norandom_wae(arma::mat X, arma::mat Y, arma::mat A, arma::mat Lambda);
RcppExport SEXP _netpanel_compute_beta_norandom_wae(SEXP XSEXP, SEXP YSEXP, SEXP ASEXP, SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_beta_norandom_wae(X, Y, A, Lambda));
    return rcpp_result_gen;
END_RCPP
}
// compute_sigma2_norandom_wae
double compute_sigma2_norandom_wae(arma::vec v, arma::mat Lambda);
RcppExport SEXP _netpanel_compute_sigma2_norandom_wae(SEXP vSEXP, SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sigma2_norandom_wae(v, Lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_dynam_wae_search
double pnam_ll_dynam_wae_search(arma::vec Y, arma::mat X, arma::mat W, arma::mat L, arma::mat B, double n, double t, double rho, double delta, double phi, double lambda);
RcppExport SEXP _netpanel_pnam_ll_dynam_wae_search(SEXP YSEXP, SEXP XSEXP, SEXP WSEXP, SEXP LSEXP, SEXP BSEXP, SEXP nSEXP, SEXP tSEXP, SEXP rhoSEXP, SEXP deltaSEXP, SEXP phiSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_dynam_wae_search(Y, X, W, L, B, n, t, rho, delta, phi, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pnam_ll_dynam_wae
double pnam_ll_dynam_wae(arma::mat netA, arma::mat netB, double sigma2, arma::vec e, double n, double t);
RcppExport SEXP _netpanel_pnam_ll_dynam_wae(SEXP netASEXP, SEXP netBSEXP, SEXP sigma2SEXP, SEXP eSEXP, SEXP nSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type netA(netASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type netB(netBSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(pnam_ll_dynam_wae(netA, netB, sigma2, e, n, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netpanel_omega", (DL_FUNC) &_netpanel_omega, 3},
    {"_netpanel_netfilter", (DL_FUNC) &_netpanel_netfilter, 2},
    {"_netpanel_compute_v", (DL_FUNC) &_netpanel_compute_v, 4},
    {"_netpanel_compute_beta", (DL_FUNC) &_netpanel_compute_beta, 4},
    {"_netpanel_compute_sigma2", (DL_FUNC) &_netpanel_compute_sigma2, 2},
    {"_netpanel_pnam_ll_rule_search", (DL_FUNC) &_netpanel_pnam_ll_rule_search, 7},
    {"_netpanel_pnam_ll_rule", (DL_FUNC) &_netpanel_pnam_ll_rule, 6},
    {"_netpanel_omega_rulewae", (DL_FUNC) &_netpanel_omega_rulewae, 5},
    {"_netpanel_pnam_ll_rulewae_search", (DL_FUNC) &_netpanel_pnam_ll_rulewae_search, 9},
    {"_netpanel_pnam_ll_rulewae", (DL_FUNC) &_netpanel_pnam_ll_rulewae, 6},
    {"_netpanel_netfilter_dpnam", (DL_FUNC) &_netpanel_netfilter_dpnam, 5},
    {"_netpanel_compute_beta_norandom", (DL_FUNC) &_netpanel_compute_beta_norandom, 3},
    {"_netpanel_compute_sigma2_norandom", (DL_FUNC) &_netpanel_compute_sigma2_norandom, 1},
    {"_netpanel_pnam_ll_dynam_search", (DL_FUNC) &_netpanel_pnam_ll_dynam_search, 9},
    {"_netpanel_pnam_ll_dynam", (DL_FUNC) &_netpanel_pnam_ll_dynam, 5},
    {"_netpanel_B_dpnam", (DL_FUNC) &_netpanel_B_dpnam, 2},
    {"_netpanel_compute_beta_norandom_wae", (DL_FUNC) &_netpanel_compute_beta_norandom_wae, 4},
    {"_netpanel_compute_sigma2_norandom_wae", (DL_FUNC) &_netpanel_compute_sigma2_norandom_wae, 2},
    {"_netpanel_pnam_ll_dynam_wae_search", (DL_FUNC) &_netpanel_pnam_ll_dynam_wae_search, 11},
    {"_netpanel_pnam_ll_dynam_wae", (DL_FUNC) &_netpanel_pnam_ll_dynam_wae, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_netpanel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
