# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omega <- function(theta, n, t) {
    .Call(`_netpanel_omega`, theta, n, t)
}

netfilter <- function(W, rho) {
    .Call(`_netpanel_netfilter`, W, rho)
}

compute_v <- function(A, beta, X, Y) {
    .Call(`_netpanel_compute_v`, A, beta, X, Y)
}

compute_beta <- function(A, omegainv, X, Y) {
    .Call(`_netpanel_compute_beta`, A, omegainv, X, Y)
}

compute_sigma2 <- function(v, omegainv) {
    .Call(`_netpanel_compute_sigma2`, v, omegainv)
}

pnam_ll_rule_search <- function(Y, X, W, n, t, rho, theta) {
    .Call(`_netpanel_pnam_ll_rule_search`, Y, X, W, n, t, rho, theta)
}

pnam_ll_rule <- function(netA, sigma2, v, omega, n, t) {
    .Call(`_netpanel_pnam_ll_rule`, netA, sigma2, v, omega, n, t)
}

omega_rulewae <- function(theta, n, t, W1, lambda) {
    .Call(`_netpanel_omega_rulewae`, theta, n, t, W1, lambda)
}

pnam_ll_rulewae_search <- function(Y, X, W, W1, n, t, rho, theta, lambda) {
    .Call(`_netpanel_pnam_ll_rulewae_search`, Y, X, W, W1, n, t, rho, theta, lambda)
}

pnam_ll_rulewae <- function(netA, sigma2, v, omega, n, t) {
    .Call(`_netpanel_pnam_ll_rulewae`, netA, sigma2, v, omega, n, t)
}

netfilter_dpnam <- function(W, L, rho, delta, phi) {
    .Call(`_netpanel_netfilter_dpnam`, W, L, rho, delta, phi)
}

compute_beta_norandom <- function(X, Y, A) {
    .Call(`_netpanel_compute_beta_norandom`, X, Y, A)
}

compute_sigma2_norandom <- function(v) {
    .Call(`_netpanel_compute_sigma2_norandom`, v)
}

pnam_ll_dynam_search <- function(Y, X, W, L, n, t, rho, delta, phi) {
    .Call(`_netpanel_pnam_ll_dynam_search`, Y, X, W, L, n, t, rho, delta, phi)
}

pnam_ll_dynam <- function(netA, sigma2, v, n, t) {
    .Call(`_netpanel_pnam_ll_dynam`, netA, sigma2, v, n, t)
}

B_dpnam <- function(B, lambda) {
    .Call(`_netpanel_B_dpnam`, B, lambda)
}

compute_beta_norandom_wae <- function(X, Y, A, Lambda) {
    .Call(`_netpanel_compute_beta_norandom_wae`, X, Y, A, Lambda)
}

compute_sigma2_norandom_wae <- function(v, Lambda) {
    .Call(`_netpanel_compute_sigma2_norandom_wae`, v, Lambda)
}

pnam_ll_dynam_wae_search <- function(Y, X, W, L, B, n, t, rho, delta, phi, lambda) {
    .Call(`_netpanel_pnam_ll_dynam_wae_search`, Y, X, W, L, B, n, t, rho, delta, phi, lambda)
}

pnam_ll_dynam_wae <- function(netA, netB, sigma2, e, n, t) {
    .Call(`_netpanel_pnam_ll_dynam_wae`, netA, netB, sigma2, e, n, t)
}

