# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omega <- function(theta, n, t) {
    .Call(`_netpanel_omega`, theta, n, t)
}

netfilter <- function(W, rho) {
    .Call(`_netpanel_netfilter`, W, rho)
}

gls_compute_v <- function(A, beta, X, Y) {
    .Call(`_netpanel_gls_compute_v`, A, beta, X, Y)
}

gls_compute_beta <- function(A, omegainv, X, Y, random) {
    .Call(`_netpanel_gls_compute_beta`, A, omegainv, X, Y, random)
}

gls_compute_sigma2 <- function(v, omegainv, random) {
    .Call(`_netpanel_gls_compute_sigma2`, v, omegainv, random)
}

pnam_ll_random_find <- function(Y, X, W, n, t, rho, theta) {
    .Call(`_netpanel_pnam_ll_random_find`, Y, X, W, n, t, rho, theta)
}

pnam_ll_random <- function(netA, sigma2, v, omega, n, t) {
    .Call(`_netpanel_pnam_ll_random`, netA, sigma2, v, omega, n, t)
}

pnam_ll_fixed_find <- function(Y, X, W, n, t, rho) {
    .Call(`_netpanel_pnam_ll_fixed_find`, Y, X, W, n, t, rho)
}

pnam_ll_fixed <- function(netA, sigma2, v, n, t) {
    .Call(`_netpanel_pnam_ll_fixed`, netA, sigma2, v, n, t)
}

create_B <- function(W2, lambda) {
    .Call(`_netpanel_create_B`, W2, lambda)
}

create_LAMBDA <- function(B) {
    .Call(`_netpanel_create_LAMBDA`, B)
}

gls_compute_e <- function(A, beta, B, X, Y) {
    .Call(`_netpanel_gls_compute_e`, A, beta, B, X, Y)
}

gls_compute_beta_error <- function(A, LAMBDA, X, Y) {
    .Call(`_netpanel_gls_compute_beta_error`, A, LAMBDA, X, Y)
}

gls_compute_sigma2_error <- function(v, omegainv) {
    .Call(`_netpanel_gls_compute_sigma2_error`, v, omegainv)
}

pnam_ll_fixed_error_find <- function(Y, X, W, n, t, rho, W2, lambda) {
    .Call(`_netpanel_pnam_ll_fixed_error_find`, Y, X, W, n, t, rho, W2, lambda)
}

pnam_ll_fixed_error <- function(netA, B, sigma2, e, n, t) {
    .Call(`_netpanel_pnam_ll_fixed_error`, netA, B, sigma2, e, n, t)
}

omega_error <- function(theta, n, t, W2, lambda) {
    .Call(`_netpanel_omega_error`, theta, n, t, W2, lambda)
}

pnam_ll_random_error_find <- function(Y, X, W, n, t, rho, theta, W2, lambda) {
    .Call(`_netpanel_pnam_ll_random_error_find`, Y, X, W, n, t, rho, theta, W2, lambda)
}

pnam_ll_random_error <- function(netA, sigma2, v, omega, n, t) {
    .Call(`_netpanel_pnam_ll_random_error`, netA, sigma2, v, omega, n, t)
}

